In [8]:
import pandas as pd
import numpy as np

In [174]:

df0 = pd.read_csv('marks.csv')
df0 = pd.DataFrame(df0)
df0.head(10)
df0.drop(['Chemistry'], axis=1, inplace=True)
df0.head(10)
#df0.dropna(inplace=True)

Name    Age Mathematics  Physics  English
0     Ali  23.00          72      NaN     64.0
1  Mohsin  21.26           ?     82.0     92.0
2  Muneeb  22.00          64     74.0      NaN
3  Zohaib  24.00        2000     96.0     76.0
4  Salman  26.00          81     79.0     81.0

In [175]:
df0.fillna(value={'Physics':df0['Physics'].mean(),'English':df0['English'].mean()}, inplace= True)
df0['Physics','English','Mathematics']=df0.Physics.astype('int64')
df0.replace(['?','/','2000'],100, inplace=True)
df0.head()


Name    Age Mathematics  Physics  English  \
0     Ali  23.00          72    82.75    64.00   
1  Mohsin  21.26         100    82.00    92.00   
2  Muneeb  22.00          64    74.00    78.25   
3  Zohaib  24.00         100    96.00    76.00   
4  Salman  26.00          81    79.00    81.00   

   (Physics, English, Mathematics)  
0                               82  
1                               82  
2                               74  
3                               96  
4                               79

In [388]:
marks= df0.mean(axis=1)
print('Muneed Mean Score: ',marks[2])

Muneed Mean Score:  62.0625


/var/folders/tr/t861gf951pz0q96xf1r59rkh0000gp/T/ipykernel_38115/4193631870.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  marks= df0.mean(axis=1)


In [389]:
df0['Total Marks']=df0.sum(axis=1)
df0.head()

/var/folders/tr/t861gf951pz0q96xf1r59rkh0000gp/T/ipykernel_38115/3747559274.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df0['Total Marks']=df0.sum(axis=1)


Name    Age Mathematics  Physics  English  \
0     Ali  23.00          72    82.75    64.00   
1  Mohsin  21.26         100    82.00    92.00   
2  Muneeb  22.00          64    74.00    78.25   
3  Zohaib  24.00         100    96.00    76.00   
4  Salman  26.00          81    79.00    81.00   

   (Physics, English, Mathematics)  Total Marks  
0                               82       251.75  
1                               82       277.26  
2                               74       248.25  
3                               96       292.00  
4                               79       265.00

In [85]:
df0.sort_values(by=['Name','Age','Mathematics','Physics','English'], ascending=True)

Name    Age Mathematics  Physics  English  (Physics, English)
0     Ali  23.00          72       82    64.00                  82
1  Mohsin  21.26           ?       82    92.00                  82
2  Muneeb  22.00          64       74    78.25                  74
4  Salman  26.00          81       79    81.00                  79
3  Zohaib  24.00        2000       96    76.00                  96

In [390]:
print('Total Scores\n','Ali:',df0.iloc[0,2],'\tSalman:',df0.iloc[4,2])

Total Scores
 Ali: 72 	Salman: 81


In [199]:
from sklearn.model_selection import train_test_split

In [204]:
df1=pd.read_csv('glass.csv')
df1.shape
print(df1.isna().sum())
df1.head(10)
#df1.columns

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64


RI     Na    Mg    Al     Si     K    Ca   Ba    Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.00     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.00     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.00     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.00     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.00     1
5  1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.0  0.26     1
6  1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.0  0.00     1
7  1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.0  0.00     1
8  1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.0  0.00     1
9  1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.0  0.11     1

In [380]:
y= np.asarray(df1[['Type']])
x= np.asarray(df1[['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe']])

In [381]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [382]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [383]:
def modelin(nu):
    knn = KNeighborsClassifier(n_neighbors=nu, weights='uniform', algorithm='auto', 
                               leaf_size=30,p=2, metric='minkowski', metric_params=None, n_jobs=None)
    knn.fit(X_train,y_train)
    y_prediction = knn.predict(X_test)
    #training_prediction = knn.predict(y_train)

    accuracy = accuracy_score(y_test,y_prediction)
    print(accuracy)

    cm_knn = confusion_matrix(y_test,y_prediction)

In [384]:
modelin(1)
modelin(2)
modelin(3)
modelin(4)
modelin(5)



0.673469387755102
0.673469387755102
0.6530612244897959
0.6122448979591837
0.6122448979591837


/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A col

# K-Fold Split

In [387]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)

for trian_index,test_index in kf.split(x):
    X_train,X_test = x[trian_index], x[test_index]
    y_train,y_test = y[trian_index], y[test_index]


# Classification Report

In [253]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           1       0.58      0.68      0.62        22
           2       0.76      0.59      0.67        22
           3       0.33      0.40      0.36         5

    accuracy                           0.61        49
   macro avg       0.56      0.56      0.55        49
weighted avg       0.64      0.61      0.62        49



# Decision Tree

In [269]:
from sklearn.tree import DecisionTreeClassifier

In [286]:
dtree= DecisionTreeClassifier(criterion='gini', splitter='best', max_depth=None,
                                                     min_samples_split=2, min_samples_leaf=1, 
                                                     min_weight_fraction_leaf=0.0, max_features=None,
                                                     random_state=None, max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)
dtree.fit(X_train,y_train)
dt_prediction= dtree.predict(X_test)
dt_accuracy = accuracy_score(y_test,dt_prediction)
print(dt_accuracy)
cm_dtree = confusion_matrix(y_test, dt_prediction)

0.6326530612244898


In [279]:
dt_prediction= dtree.predict(X_test)
dt_accuracy = accuracy_score(y_test,dt_prediction)
cm_dtree = confusion_matrix(y_test, dt_prediction)
print(dt_accuracy)

0.6122448979591837


In [287]:
#Entropy
dtree= DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None,
                                                     min_samples_split=2, min_samples_leaf=1, 
                                                     min_weight_fraction_leaf=0.0, max_features=None,
                                                     random_state=None, max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)
dtree.fit(X_train,y_train)
dt_prediction= dtree.predict(X_test)
dt_accuracy = accuracy_score(y_test,dt_prediction)
print(dt_accuracy)
cm_dtree = confusion_matrix(y_test, dt_prediction)

0.6938775510204082


# K means Clustering

In [371]:
colo = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi',
                                         'pedigree', 'age', 'label']
df2= pd.read_csv('pima.csv',names= colo)
df2= pd.DataFrame(df2)
display(df2)

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0           6      148  72    35        0  33.6     0.627   50      1
1           1       85  66    29        0  26.6     0.351   31      0
2           8      183  64     0        0  23.3     0.672   32      1
3           1       89  66    23       94  28.1     0.167   21      0
4           0      137  40    35      168  43.1     2.288   33      1
..        ...      ...  ..   ...      ...   ...       ...  ...    ...
763        10      101  76    48      180  32.9     0.171   63      0
764         2      122  70    27        0  36.8     0.340   27      0
765         5      121  72    23      112  26.2     0.245   30      0
766         1      126  60     0        0  30.1     0.349   47      1
767         1       93  70    31        0  30.4     0.315   23      0

[768 rows x 9 columns]

In [372]:
y=np.asarray(df2[['label']])
X=df2[['pregnant', 'insulin', 'bmi', 'skin', 'age','glucose','bp','pedigree']]

In [373]:
from sklearn.cluster import KMeans

In [376]:
def K_cluster(clt):
    kmeans = KMeans(n_clusters=clt, init='k-means++', n_init=10, max_iter=300, tol=0.0001, 
           verbose=0, random_state=None, copy_x=True, algorithm='auto')
    kmeans.fit(X)

    km_labels = kmeans.labels_
    #print(km_labels)
    cm_kmean = confusion_matrix(km_labels,y)
    print(cm_kmean)


In [379]:
for ctr in range(9):
    K_cluster(ctr+1)
    
    
    

[[500 268]
 [  0   0]]
[[421 182]
 [ 79  86]]
[[137  98   0]
 [347 148   0]
 [ 16  22   0]]
[[275 142   0   0]
 [ 10  14   0   0]
 [ 55  59   0   0]
 [160  53   0   0]]
[[158  25   0   0   0]
 [  6  12   0   0   0]
 [ 70  70   0   0   0]
 [245 140   0   0   0]
 [ 21  21   0   0   0]]
[[202  67   0   0   0   0]
 [ 69  69   0   0   0   0]
 [  6  12   0   0   0   0]
 [151  25   0   0   0   0]
 [ 51  74   0   0   0   0]
 [ 21  21   0   0   0   0]]
[[ 20  16   0   0   0   0   0]
 [ 69  69   0   0   0   0   0]
 [  6  12   0   0   0   0   0]
 [ 22  22   0   0   0   0   0]
 [149  24   0   0   0   0   0]
 [184  54   0   0   0   0   0]
 [ 50  71   0   0   0   0   0]]
[[  2   1   0   0   0   0   0   0]
 [ 69  66   0   0   0   0   0   0]
 [182  54   0   0   0   0   0   0]
 [ 24  25   0   0   0   0   0   0]
 [147  23   0   0   0   0   0   0]
 [  6  12   0   0   0   0   0   0]
 [ 20  16   0   0   0   0   0   0]
 [ 50  71   0   0   0   0   0   0]]
[[174  53   0   0   0   0   0   0   0]
 [ 45  46   0 

# Support Vector machine


In [367]:
from sklearn.svm import SVC


In [370]:
svc=SVC(C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=- 1, decision_function_shape='ovr', break_ties=False, random_state=None)
svc.fit(X_train,y_train)

y_pred=svc.predict(X_test)
y_trainpred=svc.predict(X_train)

cm_svc=confusion_matrix(y_test,y_pred)
print("True Possitives: ", cm_svc[0][0],"True Negatives: ",cm_svc[0][1])
print("False Possitives: ", cm_svc[1][0],"False Negatives: ",cm_svc[1][1])
accuracy_svc=accuracy_score(y_test,y_pred)
print("SVM Accuracy: ",accuracy_svc)

True Possitives:  0 True Negatives:  22
False Possitives:  0 False Negatives:  22
SVM Accuracy:  0.4489795918367347


/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [391]:
from sklearn.neural_network import MLPClassifier

In [402]:
clf = MLPClassifier(hidden_layer_sizes=(150,100,50), activation='relu', solver='adam', alpha=0.0001, 
              batch_size='auto', learning_rate='constant', learning_rate_init=0.001, 
              power_t=0.5, max_iter=300, shuffle=True, random_state=None, tol=0.0001, 
              verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, 
              early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, 
              epsilon=1e-08, n_iter_no_change=10, max_fun=15000)
clf.fit(X_train,y_train)
clf_pre=clf.predict(X_test)
clf_acc = accuracy_score(y_test,clf_pre)
print(clf_acc)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.25


/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


In [392]:
help(MLPClassifier)

Help on class MLPClassifier in module sklearn.neural_network._multilayer_perceptron:

class MLPClassifier(sklearn.base.ClassifierMixin, BaseMultilayerPerceptron)
 |  MLPClassifier(hidden_layer_sizes=(100,), activation='relu', *, solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000)
 |  
 |  Multi-layer Perceptron classifier.
 |  
 |  This model optimizes the log-loss function using LBFGS or stochastic
 |  gradient descent.
 |  
 |  .. versionadded:: 0.18
 |  
 |  Parameters
 |  ----------
 |  hidden_layer_sizes : tuple, length = n_layers - 2, default=(100,)
 |      The ith element represents the number of neurons in the ith
 |      hidden layer.
 |  
 |  activation : {'identity